# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
 #/Resources/config/services.yml
imports:
    - { resource: packages/bucket_config.yaml }

parameters:
    locale: 'en'
    git_repo_store: '%kernel.project_dir%/public/lafesa'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    app.git_service_factory:
        class: App\Service\GitServiceFactory
        arguments: [ "@app.git_logger" ]
        

    git_service_factory:
        alias: app.git_service_factory

    app.repo_service:
        class: App\Service\RepoService
        arguments: [ "@doctrine" ]

    repo_service:
        alias: app.repo_service

    app.git_logger:
        class: App\Logger\GitLogger

    git_logger:
        alias: app.git_logger

    app.git_collector:
        class: App\DataCollector\GitCollector
        arguments: [ "@app.git_logger" ]
        public: false
        tags:
            - { name: data_collector, template: 'DataCollector/template.html.twig', id: "git.collector" }

    app.data_object_factory:
        class: App\DataObject\DataObjectFactory
        arguments: [ "@git_service_factory" ]